### ISSUE TITLE
In IndividualEvent records, Meet Manager stores the fractional part of points_scored_finals in an area documented as "future use"

### ISSUE THREAD

**Issue by ericvsmith** [tdsmith/sdif#13]
In IndividualEvent records, Meet Manager stores the fractional part of points_scored_finals in columns 151-152.

In the "Individual Event Record" (D0) section, line 1120 of sdifv3f.txt says "146/15                 future use".

Here's an example (name overwritten with X's), where the points were 4.50, due to a tie:
```
D01PV      XXXXXXX, XXXXXXX            050301XXX*XXAUSA0503200112FF  503 34 111207222023   46.28S                     45.03S     1 1     8  4.   2  0350    NN21
```
It's weird because columns 139-133 (points_scored_finals) are a decimal and contain `  4.`. MM doesn't store the score as `4.50`, but instead puts the fractional value `50` in a separate, undocumented field. Maybe they did this because the 4 character points_scored_finals field couldn't store a value like `100.5` or `10.33`. Who knows what they were thinking?

I've added this to IndividualEvent:
```
    centipoints_scored_finals: Optional[int] = spec(151, 2)
```
And my tests pass. Of course I have to manually calculate the points as `record.points_scored_finals + record.centipoints_scored_finals / Decimal(100)`, but that's okay with me.

Here's another record, with a score of 3.0:
```
D01PV      XXXXXXX, XXXXXXX            070405XXX*XXAUSA07042005 7FF  251  6 UN0807222023   21.37S                     22.47S     1 1    10  3.   4  0100    NN71
```
Note that points_scored_finals is `  3.`, and my centipoints_scored_finals is `00`. As near as I can tell, MM always puts `00` in this field if there are no fractional points.

I'm not sure the best way to handle this. It seems wrong to just add this undocumented field, but MM is definitely using it. I'm open to ideas with ways to mark this as a MM extension, and make accepting it opt-in. Maybe just having a leading underscore in the field name is sufficient? But what if someone else uses this field for a non-numeric value?

I just realized that maybe I can subclass IndividualEvent and add my centipoints_scored_finals field. I'll need to delete the assert at https://github.com/tdsmith/sdif/blob/78b86ef8afe4b05553faaef7ef1e7d1df12d1aac/src/sdif/model_meta.py#L99 where you make sure a model isn't being re-registered, but in principle I think it should work. I'll investigate and get back to you.

**Comment by ericvsmith** [comment]
@tdsmith : My subclassing idea works well (subject to removing the assert, as I mentioned above). Curious as to your thoughts. Maybe add a parameter to `@model` saying "yes, I want to override the previously defined model with this identifier"?

This would basically give me an escape hatch where I can support any wacky MM behavior. Although maybe others could benefit from these subclasses, and they shouldn't be "locked away" inside my code.

**Comment by tdsmith** [comment]
Thanks for the investigation! _I'm_ mostly concerned about communicating with Meet Manager and I don't think this is a huge ecosystem so I'd be happy to just slap `centipoints_scored_finals` on the model with a comment and call it a day. I'd appreciate capturing your experience here!

**Comment by ericvsmith** [comment]
I'm in a rush this morning and will do some more testing tonight. I wanted to get this started so you could take a look.

**Comment by ericvsmith** [comment]
After fixing a copy and paste error, my tests pass. Feel free to modify the comment and commit this, and/or do whatever testing you'd like. Thanks!

**Comment by ericvsmith** [comment]
Thanks for doing the release, @tdsmith !

Everything is working great on my end. This should be the end of what I need to do for a while. In a few months I'm going to be working on writing sdif files for MM, and I may have some more issues then. I thought MM required checksums on each line, but I guess not, if you're using it without writing them. I do have code to produce and validate the checksums: maybe when the time comes we can make that an option when writing files, if needed.
